kernel:
  image: linuxkit/kernel:4.9.39
  cmdline: "console=ttyS0 console=tty0 page_poison=1"
init:
  - linuxkit/init:12348442d56c2ee9abf13ff38dff2e36b515bd1e
  - linuxkit/runc:e2488d48f4070d3f455471c191b27d33a95f054d
  - linuxkit/containerd:22ca68df25ad4f65746e68466de23e0f24e6e93a
  - linuxkit/ca-certificates:67acf038c44bb191ebb704ec7bb39a1524052cdf
onboot:
  - name: sysctl
    image: linuxkit/sysctl:d1a43c7c91e92374766f962dc8534cf9508756b0
  - name: format
    image: linuxkit/format:efafddf9bc6165b5efaf09c532c15a1100a10e61
  - name: mount
    image: linuxkit/mount:54990a6a69cb3ead4da8a9c1f0b651e27aea8d3f
    command: ["/usr/bin/mountie", "/var/lib/etcd"]
  - name: dhcpcd
    image: linuxkit/dhcpcd:17423c1ccced74e3c005fd80486e8177841fe02b
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:f5d4299909b159db35f72547e4ae70bd76c42c6c
services:
  - name: rngd
    image: linuxkit/rngd:1516d5d70683a5d925fe475eb1b6164a2f67ac3b
  - name: ntpd
    image: linuxkit/openntpd:2874b66c9fa51fa5b4d11c8b50441eb94ee22a5a
  - name: node_exporter
    image: linuxkit/node_exporter:a058fe1c6a4440a9689022a9fd7cffdcfd56d52c
  - name: etcd
    image: moby/etcd
    capabilities:
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
     - CAP_SYS_ADMIN
     - CAP_MKNOD
    net: host
    binds:
     - /var/lib/etcd:/var/lib/etcd
     - /var/config/etcd:/etc/etcd
trust:
  org:
    - linuxkit
