kernel:
  image: "linuxkit/kernel:4.9.34"
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:e7f7119d21c423d64db186fe6fe011edd7422418
  - linuxkit/runc:291131ec026430371e7c36165c3f43734fbc2541
  - linuxkit/containerd:1e3e8f207421de8deac8cedc26a138d6b1661a0d
onboot:
  - name: sysctl
    image: linuxkit/sysctl:3aa6bc663c2849ef239be7d941d3eaf3e6fcc018
  - name: dhcp-client
    image: miragesdk/dhcp-client:22aa9d527820534295a8cd59901c0c5197af6585
    net: host
    capabilities:
     - CAP_NET_ADMIN # to bring eth0 up
     - CAP_NET_RAW   # to read /dev/eth0
     - CAP_SYS_ADMIN # for runc (unshare)
     - CAP_SETGID    # for runc (setns)
    mounts: # for runc
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /var/run/dhcp-client:/data
     - /usr/bin/runc:/usr/bin/runc # for runc
     - /run/runc:/run/runc         # for runc
     - /sbin:/sbin   # for ifconfig
     - /bin:/bin     # for ifconfig
     - /lib:/lib     # for ifconfig
services:
  - name: sshd
    image: "linuxkit/sshd:f095b62ddca658e99d5751872c933ef3d5d18cec"
  - name: getty
    image: "linuxkit/getty:6cbeee0392b0670053ce2bf05a5a0d67ec2bce05"
    env:
     - INSECURE=true
files:
  - path: var/run/dhcp-client/README
    contents: 'data for dhcp-client'
  - path: root/.ssh/authorized_keys
    contents: '#your SSH key here'
