kernel:
  image: linuxkit/kernel:4.9.39
  cmdline: "console=ttyS0 console=tty0 page_poison=1"
init:
  - linuxkit/init:12348442d56c2ee9abf13ff38dff2e36b515bd1e # with runc, logwrite, startmemlogd
  - linuxkit/runc:e2488d48f4070d3f455471c191b27d33a95f054d
  - linuxkit/containerd:22ca68df25ad4f65746e68466de23e0f24e6e93a
  - linuxkit/ca-certificates:67acf038c44bb191ebb704ec7bb39a1524052cdf
  - linuxkit/memlogd:9b5834189f598f43c507f6938077113906f51012
onboot:
  - name: sysctl
    image: linuxkit/sysctl:d1a43c7c91e92374766f962dc8534cf9508756b0
  - name: binfmt
    image: linuxkit/binfmt:257b5174a8e33bc62d5448cc026d72cae3713628
  - name: dhcpcd
    image: linuxkit/dhcpcd:17423c1ccced74e3c005fd80486e8177841fe02b
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:1516d5d70683a5d925fe475eb1b6164a2f67ac3b
  - name: nginx
    image: nginx:alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
files:
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  image:
    - linuxkit/kernel
    - linuxkit/init
    - linuxkit/runc
    - linuxkit/containerd
    - linuxkit/ca-certificates
    - linuxkit/sysctl
    - linuxkit/binfmt
    - linuxkit/dhcpcd
    - linuxkit/rngd
