kernel:
  image: linuxkit/kernel-ima:4.11.1-186dd3605ee7b23214850142f8f02b4679dbd148
  cmdline: "console=ttyS0 console=tty0 page_poison=1 ima_appraise=enforce_ns"
init:
  - linuxkit/init:4dcee04c04c900a5796dc719f8d16fea7e771059
  - linuxkit/runc:e2488d48f4070d3f455471c191b27d33a95f054d
  - linuxkit/containerd:22ca68df25ad4f65746e68466de23e0f24e6e93a
  - linuxkit/ca-certificates:67acf038c44bb191ebb704ec7bb39a1524052cdf
  - linuxkit/ima-utils:dfeb3896fd29308b80ff9ba7fe5b8b767e40ca29
onboot:
  - name: sysctl
    image: linuxkit/sysctl:d1a43c7c91e92374766f962dc8534cf9508756b0
  - name: binfmt
    image: linuxkit/binfmt:257b5174a8e33bc62d5448cc026d72cae3713628
  - name: dhcpcd
    image: linuxkit/dhcpcd:17423c1ccced74e3c005fd80486e8177841fe02b
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:1516d5d70683a5d925fe475eb1b6164a2f67ac3b
  - name: nginx
    image: nginx:alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
files:
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  image:
    - linuxkit/kernel
    - linuxkit/init
    - linuxkit/runc
    - linuxkit/containerd
    - linuxkit/ca-certificates
    - linuxkit/sysctl
    - linuxkit/binfmt
    - linuxkit/dhcpcd
    - linuxkit/rngd
