kernel:
  image: linuxkit/kernel:4.9.39
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:4dcee04c04c900a5796dc719f8d16fea7e771059
  - linuxkit/runc:e2488d48f4070d3f455471c191b27d33a95f054d
  - linuxkit/containerd:22ca68df25ad4f65746e68466de23e0f24e6e93a
  - linuxkit/ca-certificates:67acf038c44bb191ebb704ec7bb39a1524052cdf
onboot:
  - name: sysctl
    image: linuxkit/sysctl:d1a43c7c91e92374766f962dc8534cf9508756b0
    binds:
     - /etc/sysctl.d/01-swarmd.conf:/etc/sysctl.d/01-swarmd.conf
  - name: dhcpcd
    image: linuxkit/dhcpcd:17423c1ccced74e3c005fd80486e8177841fe02b
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:efafddf9bc6165b5efaf09c532c15a1100a10e61
  - name: mount
    image: linuxkit/mount:54990a6a69cb3ead4da8a9c1f0b651e27aea8d3f
    command: ["/usr/bin/mountie", "/var/lib/swarmd"]
  - name: metadata
    image: linuxkit/metadata:f5d4299909b159db35f72547e4ae70bd76c42c6c
services:
  - name: getty
    image: linuxkit/getty:58620cff1b0bf8b5d144d087602115e996f18a02
    env:
     - INSECURE=true
  - name: qemu-ga
    image: linuxkit/qemu-ga:585e4f0161a4df7583d5e0479d7621040c1ee140
    binds:
      - /dev/vport0p1:/dev/vport0p1
  - name: rngd
    image: linuxkit/rngd:1516d5d70683a5d925fe475eb1b6164a2f67ac3b
  - name: ntpd
    image: linuxkit/openntpd:2874b66c9fa51fa5b4d11c8b50441eb94ee22a5a
  - name: weave
    image: weaveworks/weave:2.0.1@sha256:2d70caac7db33365482cc923d40ff8d3ec1238ae7fe06a00b3dde310d09f226e # Must match swarmd/Dockerfile
    command: ["/bin/sh", "/home/weave/weaver-wrapper"]
    capabilities:
     - all
    pid: host
    binds:
      - /usr/local/bin/weaver-wrapper:/home/weave/weaver-wrapper
      - /var:/var
      - /var/lib/swarmd:/weavedb
  - name: swarmd
    image: linuxkitprojects/swarmd:cce587b5e67b7d3e088a2e527dafc5ad3edb6502
    command: ["/usr/bin/swarmd", "--containerd-addr=/run/containerd/containerd.sock", "--log-level=debug", "--state-dir=/var/lib/swarmd"]
    capabilities:
     - all
    pid: host
    binds:
      - /tmp:/tmp
      - /run/containerd/containerd.sock:/run/containerd/containerd.sock
      - /var/lib/containerd:/var/lib/containerd
      - /var/lib/swarmd:/var/lib/swarmd
      - /etc/resolv.conf:/etc/resolv.conf
files:
  - path: /etc/sysctl.d/01-swarmd.conf
    contents: 'net.ipv4.ip_forward = 1'
  - path: usr/local/bin/weaver-wrapper
    contents: |
      /home/weave/weaver \
          --weave-bridge=weave \
          --datapath=datapath \
          --docker-api="" \
          --ipalloc-range=192.168.106.0/24 \
          --http-addr=127.0.0.1:6784 \
          --status-addr=127.0.0.1:6782 &

      while [ ! -e /sys/class/net/weave/ ] ; do
         sleep 1s
      done

      /home/weave/weave --local expose net:default
      wait %1
